# Generated by Django 5.2.13 on 2026-04-11 11:08

import apps.core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accuracy", "Точность"),
                            ("speed", "Скорость"),
                            ("capacity", "Ёмкость"),
                            ("manageability", "Управляемость"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight", models.PositiveSmallIntegerField(default=1)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_self_audit", models.BooleanField(default=True)),
                ("hint", models.TextField(blank=True)),
                ("check_note", models.TextField(blank=True)),
                ("impact_text", models.TextField(blank=True)),
                ("self_recommendation", models.TextField(blank=True)),
                ("pro_recommendation", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("self", "Self-audit (заказчик)"),
                            ("pro", "Pro-аудит (консультант)"),
                        ],
                        default="self",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("completed", "Завершён"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("client_company", models.CharField(blank=True, max_length=200)),
                ("client_email", models.EmailField(max_length=254)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("total_score", models.FloatField(blank=True, null=True)),
                ("total_grade", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "client_email"],
                        name="core_audits_status_5a75f9_idx",
                    ),
                    models.Index(
                        fields=["mode", "completed_at"],
                        name="core_audits_mode_26e175_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.models.audit_report_upload_to,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("summary", models.JSONField(default=dict)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="core.auditsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("text", models.CharField(max_length=500)),
                ("score_percent", models.IntegerField()),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_answer_text", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="audit_photos/%Y/%m/%d/"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.answeroption",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.auditsession",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                fields=("question", "code"),
                name="unique_answer_option_code_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="answeroption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"),
                name="unique_answer_option_order_per_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="useranswer",
            constraint=models.UniqueConstraint(
                fields=("session", "question"),
                name="unique_user_answer_per_session_question",
            ),
        ),
    ]
