# Generated by Django 5.2.13 on 2026-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_answeroption_after_answer_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullAuditLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "contact",
                    models.CharField(max_length=500, verbose_name="Email или телефон"),
                ),
                (
                    "preferred_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Телефон")],
                        max_length=16,
                        verbose_name="Предпочитаемый способ связи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, verbose_name="Письмо отправлено"
                    ),
                ),
                (
                    "email_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Ошибка отправки почты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на полный аудит",
                "verbose_name_plural": "Заявки на полный аудит",
                "ordering": ["-created_at"],
            },
        ),
    ]
