# Generated by Django 5.2.13 on 2026-04-13 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_full_audit_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="WmsChecklistSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сессия WMS чек-листа",
                "verbose_name_plural": "Сессии WMS чек-листа",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WmsChecklistAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ready", "Готово"),
                            ("in_progress", "В процессе"),
                            ("not_ready", "Не готово"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.wmschecklistsession",
                    ),
                ),
            ],
            options={
                "ordering": ["item_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "item_number"),
                        name="unique_wms_answer_per_session_item",
                    )
                ],
            },
        ),
    ]
