# Generated by Django 5.2.13 on 2026-04-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_wms_checklist_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=64)),
                ("recipient_group", models.CharField(default="internal", max_length=64)),
                ("recipients", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("skipped", "Пропущено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("message_id", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["event_type", "entity_id"], name="core_notifi_event_t_8388a4_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["status", "created_at"], name="core_notifi_status_7f65de_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationlog",
            constraint=models.UniqueConstraint(
                fields=("event_type", "entity_id", "recipient_group"),
                name="uniq_notification_event_entity_group",
            ),
        ),
    ]
