# Generated by Django 5.2.13 on 2026-04-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_notificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditreport",
            name="email_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
