# Generated by Django 4.2.29 on 2026-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthSelfAuditResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("answers_json", models.JSONField(default=dict)),
                ("result_json", models.JSONField(default=dict)),
                ("overall_index", models.IntegerField()),
                ("overall_zone", models.CharField(max_length=16)),
                ("accuracy_percent", models.IntegerField()),
                ("speed_percent", models.IntegerField()),
                ("capacity_percent", models.IntegerField()),
                ("manageability_percent", models.IntegerField()),
            ],
            options={
                "verbose_name": "Результат self-audit",
                "verbose_name_plural": "Результаты self-audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
